### ISSUE TITLE
dev-util/rust-analyzer: requires rust version 1.46.0

### ISSUE THREAD

**Issue by TheGreatMcPain** [leonardohn/gentoo-overlay#1]
[Rust 1.46.0](https://github.com/rust-lang/rust/releases/tag/1.46.0) supports the use of loops within const functions.

Thus, `rust-analyzer` fails to compile with earlier versions of Rust with this error.

```
error[E0658]: `while` is not allowed in a `const fn`
  --> crates/parser/src/token_set.rs:15:9
   |
15 | /         while i < kinds.len() {
16 | |             res |= mask(kinds[i]);
17 | |             i += 1
18 | |         }
   | |_________^
   |
   = note: see issue #52000 <https://github.com/rust-lang/rust/issues/52000> for more information
```

**Comment by leonardohn** [comment]
Thanks for the contribution, I will fix it on today's update. By the way, beside this issue, it rust-analyzer working fine for you?

**Comment by TheGreatMcPain** [comment]
I was able to get `youcompleteme`, from my overlay, to communicate with it, but it can't find where the rust sources are.

From what I could find, Gentoo installs the rust sources in `/usr/lib64/rust-1.46.0/rustlib/src`.

`rust-analyzer` searches `$(rustc --print sysroot)/lib/rustlib/src/rust`, but it also checks the `RUST_SRC_PATH` environment variable.

#### UPDATE
I was able to get it to work with YouCompleteMe by exporting `RUST_SRC_PATH=/usr/lib64/rust-1.46.0/rustlib/src/rust/src`, but I now need to figure out how to set `rust-analyzer`'s server port, because it keeps randomly picking really high port numbers which prevents YouCompleteMe from making a successful connection.

**Comment by leonardohn** [comment]
I've already reported the problem at https://github.com/gentoo/gentoo-rust/issues/502, but unfortunately no official solutions so far; However, you could temporarily set `export RUST_SRC_PATH=$(rustc --print target-libdir)/../../src/rust/src`, so you won't have problems when a new Rust release comes out.

**Comment by TheGreatMcPain** [comment]
One more thing not related to this issue.

How are you creating the CRATES list for your rust-analyzer ebuild?  I've tried using cargo-ebuild, but the list ends up being incomplete.

**Comment by leonardohn** [comment]
I've submitted a pull request at https://github.com/cardoe/cargo-ebuild/pull/39, but it is not yet available on the upstream version. One way to have it working is to clone the repository and then `cargo install --bin cargo-ebuild --path <path to local repo>`.
